### ISSUE TITLE
Requirements File

### ISSUE THREAD

**Issue by jcformanek** [thu-rllab/CFCQL#2]
Hi there, could you please share more details regarding the requirements. I am struggling to get versions of packages that work with your code and can therefore no run the code. Your help will be really appreciated. Perhaps you could post the output of `pip freeze`

**Comment by cloud-qu** [comment]
[requirements1.txt](https://github.com/thu-rllab/CFCQL/files/15428921/requirements1.txt)
Hi, I think that you might be having difficulty with the continuous version. Here is a version of the requirements that is compatible with our code. I hope this helps you.

**Comment by jcformanek** [comment]
Thanks, that helps a lot.
