### ISSUE TITLE
"expert" and "mixed" dataset are exactly equal on 5m_vs_6m

### ISSUE THREAD

**Issue by jcformanek** [thu-rllab/CFCQL#3]
Hi there, thanks for sharing your code and datasets. I noticed that the "mixed" and "expert" datasets are exactly equal. I thought that maybe that was a small mistake you made while uploading the datasets. Could you please check and share the correct "mixed" dataset. 

Many thanks.

**Comment by jcformanek** [comment]
Oh, and on the other three SMAC scenarios mixed == medium.

**Comment by cloud-qu** [comment]
We acknowledge the error made in uploading the dataset. Thank you for your correction. The datasets for SMAC have been updated.

**Comment by jcformanek** [comment]
Thats great, thank you!
