### ISSUE TITLE
Can't Access the datasets that are on Baidu

### ISSUE THREAD

**Issue by jcformanek** [thu-rllab/CFCQL#4]
Hi there, it has proven to be nearly impossible to make a Baidu account and I can therefore not get access to the MPE datasets. Could you please share them via another method e.g. Google Drive? I can share a Google Drive folder with you with sufficient storage and you can upload them there. Would that work?

**Comment by cloud-qu** [comment]
We have re-uploaded the datasets for the Predator-Prey and World to Google Drive. Hope this is helpful.

**Comment by jcformanek** [comment]
Thank you very much! I can now access them.
