### ISSUE TITLE
Question for the performance

### ISSUE THREAD

**Issue by kkkaiaiai** [thu-rllab/CFCQL#5]
Dear author,

I have read your NIPS'23 paper CFCQL recently. The work was so interesting and it was attractive to me. However, I have some problems about the official code. In SC2, does final performance mean final_test_battle_won_? Why is there a gap between my results and those reported in the paper? (e.g., the following results are run on the SC2-2s3z-medium with seed = 0)

All the best

[INFO 16:13:59] my_main Recent Stats | t_env:   10054611 | Episode:    12136
cql_loss:                  0.0929       ep_length_mean:           52.9844       epsilon:                   0.0000       final_test_battle_won_mean:  0.1625
final_test_ep_length_mean: 52.9000      final_test_n_episodes:   640.0000       final_test_return_mean:   13.0961       final_test_return_std:     3.5685
grad_norm:                25.5291       lambda_mask_max:           0.2428       lambda_mask_mean:          1.0000       lambda_mask_min:           0.1814
lambda_ratio:              0.4850       loss_td:                   0.3654       n_episodes:              128.0000       negtive_sampling_mean:     4.8882
q_local_taken_mean:        0.2073       q_taken_mean:              4.7953       return_mean:              13.0893       return_std:                3.4084
target_mean:               4.9585       td_error_abs:              0.3654       test_battle_won_mean:      0.3333       test_ep_length_mean:      58.3333
test_n_episodes:          24.0000       test_return_mean:         14.6536       test_return_std:           3.9505

**Comment by cloud-qu** [comment]
Thank you for your interest in our work. 
Yes, the final performance means final_test_battle_won_mean.
We have released the [hyperparameters](https://github.com/thu-rllab/CFCQL/tree/main/discrete) for the SMAC experiments. Hope this will be helpful. 
Best regrads.
