### ISSUE TITLE
Expert data set for 3s5z

### ISSUE THREAD

**Issue by zhonghai1995** [thu-rllab/CFCQL#6]
Hi authors, thanks for your work and datasets.

I am trying to visualize the expert dataset for 3s5z, looks like its expert score is roughly between 11 and 12. is it too low for an expert policy? Thanks for your time.

![trajectory_returns_distribution_3s_vs_5z_expert](https://github.com/user-attachments/assets/d6c82bd9-11ec-4da0-8e20-4e82a73b1d00)

**Comment by cloud-qu** [comment]
Hi,

Thank you for reaching out and for your interest in our work. I have redownloaded and re-evaluated the 3s_vs_5z_expert dataset, and the mean trajectory return is approximately 21. It’s possible that there may have been an issue during your evaluation. If you encounter any further questions or need additional assistance, please don’t hesitate to contact me. I’m happy to help.


![image](https://github.com/user-attachments/assets/761a1507-f65f-4f8d-bed1-5121259617d9)

**Comment by zhonghai1995** [comment]
Thanks for your time and reply. I would double check!
